In [1]:
import numpy as np

# Cadeias com estados absorventes

## Exemplo de aplicação (pag. 32) [resolvido]

In [2]:
Q = np.array([[0.8, 0.15, 0],[0, 0.7, 0.2], [0, 0, 0.95]]); Q

array([[0.8 , 0.15, 0.  ],
       [0.  , 0.7 , 0.2 ],
       [0.  , 0.  , 0.95]])

In [3]:
R = np.array([[0.05], [0.10], [0.05]]); R

array([[0.05],
       [0.1 ],
       [0.05]])

In [4]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1. Em média, durante quanto tempo um estagiário permanece na empresa?

In [5]:
r = np.mat(I - Q) ** -1
r

matrix([[ 5.        ,  2.5       , 10.        ],
        [ 0.        ,  3.33333333, 13.33333333],
        [ 0.        ,  0.        , 20.        ]])

In [6]:
print(r[0].sum().round(3), "anos")

17.5 anos


2. Qual a probabilidade de um estagiário conseguir chegar a sócio da empresa?  

_Não é possível responder a partir da formulação anterior. Neste caso (2), podemos pensar que a probabilidade de um estagiário conseguir chegar a sócio da empresa é igual à probabilidade de sair da empresa como sócio. Assim, devemo desagregar o estado "Fora da Empresa" em dois distintos:_

**Fora não como sócio** e **Fora como sócio**

In [7]:
R_ = np.array([[0.05, 0 ], [0.10, 0], [0, 0.05]]); R_

array([[0.05, 0.  ],
       [0.1 , 0.  ],
       [0.  , 0.05]])

$(I - Q) ^{-1} \cdot R$

In [8]:
r = (np.mat(I - Q) ** -1).dot(R_)
r

matrix([[0.5       , 0.5       ],
        [0.33333333, 0.66666667],
        [0.        , 1.        ]])

In [9]:
r[0, 1] * 100 # probabilidade (em %) de um estagiário sair da empresa como sócio (é o mesmo que chegar a sócio)

49.99999999999996

3. Em média, durante quanto tempo um sócio permanecerá na empresa (nessa condição)?

In [10]:
R

array([[0.05],
       [0.1 ],
       [0.05]])

A probabilidade de um sócio sair é 0.05. Assim, o número de anos que demorará a sair é o seu inverso.

In [11]:
print(R[2][0] ** -1, "anos")

20.0 anos
